### ISSUE TITLE
QT threads related error when running in release

### ISSUE THREAD

**Issue by sofian** [sofian/drone#24]
When I compile and run in release mode under Linux Ubuntu 12.04, the program crashes. It seems to be happening only when I have a VideoOutput (Gear_TV is ok).

<pre>
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
drone: ../../src/xcb_io.c:178: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
Aborted
</pre>

I also tried running a video with a TV, pausing, adding a VideoOutput (with a ImageToTexture between). Then it doesn't crash but the VideoOutput image is blank (black) although it takes the proper width/size.

**Comment by sofian** [comment]
I found a way around (this is specific to Linux and X11).

**Comment by sofian** [comment]
Actually, this fix doesn't fix the black videooutput screen. I will open a new issue for that one.

**Comment by samsamm777** [comment]
@sofian How did you fix this?
