### ISSUE TITLE
Write compilation instructions for Mac OSX

### ISSUE THREAD

**Issue by sofian** [sofian/drone#3]
I'm trying to compile under Mac OSX. It would be nice to have a procedure. I also tried to run directly from the dron-0.3 tarball that Julien sent us by email: it works but the VideoSource isn't loaded because libavformat is missing, so I'm worried I might have to recompile FFMPEG. I'm ok with doing it but I would need a recipe on how to do it (like I did for Ubuntu, see the wiki).

**Comment by jukea** [comment]
about the mac instructions.. good idea. I think we're doing it live right
now :)

about ffmpeg : try installing ffmpeg-devel with macports (I'd officially
recommend that way to install ffmpeg for drone on a mac)

sudo port install ffmpeg-devel

it comes with the following dependencies by default :

Library Dependencies: lame, libvorbis, libopus, libogg, libtheora,
libmodplug, jack, dirac, schroedinger, openjpeg, freetype, speex, libvpx,
libsdl, bzip2, zlib, XviD, x264

On Wed, Dec 19, 2012 at 10:20 AM, sofian notifications@github.com wrote:

> I'm trying to compile under Mac OSX. It would be nice to have a procedure.
> I also tried to run directly from the dron-0.3 tarball that Julien sent us
> by email: it works but the VideoSource isn't loaded because libavformat is
> missing, so I'm worried I might have to recompile FFMPEG. I'm ok with doing
> it but I would need a recipe on how to do it (like I did for Ubuntu, see
> the wiki).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sofian/drone/issues/3.

## 

julien keable, ingénieur projets web  |  espresso communication & design
|  514.286.9696

**Comment by sofian** [comment]
Based on my experience and the closed issues I created some instructions:
https://github.com/sofian/drone/wiki/Install

Feel free to contribute. Closing this issue.
